announcer:
  enabled: true
  random: false
  interval: 6
interval-announcement:
  - one
  - two
  - three
announcements:
  one:
    actionbar:
      enabled: true
      message: "<green>This is a announcer"
    chat-message:
      - "<green>This is a announcer"
      - "<gradient:#5e4fa2:#f79459>Compatible with hex colors</gradient>"
  two:
    - "[TITLE] Title announce;Subtitle Announce;5;5;5"
    - "[ACTIONBAR] <red>This is a announcer"
    - "[MESSAGE] <red>This is a announcer"
    - "[MESSAGE] <blue>Compatible with PlaceholderAPI"
    - "[MESSAGE] <green>Name: <yellow>%player_name%"
    - "[MESSAGE] <green>Prefix: <yellow>%vault_prefix%"
  three:
    - "<green>This is a announcer"
    - "<hover:show_text:'<blue>Show minimessage page'><red>Compatible with hover text</hover>"
    - "<hover:show_text:'<blue>Click here'><Click:suggest_command:/say Hello><red>Compatible with click actions</action></hover>"