debug: "Test"
announcer:
  enabled: true
  random: false
  interval: 10
interval-announcement:
  - one
  - two
  - three
announcements:
  one:
    - "[MESSAGE] <r>"
    - "[TITLE] <aqua>Title announce;<green>Subtitle Announce;5;5;5"
    - "[ACTIONBAR] <aqua>This is a announcer"
    - "[MESSAGE] <red>This is a announcer"
    - "[MESSAGE] <r>"
  two:
    - "[MESSAGE] <r>"
    - "[TITLE] <aqua>Title announce;<green>Subtitle Announce;5;5;5"
    - "[ACTIONBAR] <red>This is a announcer"
    - "[MESSAGE] <red>This is a announcer"
    - "[MESSAGE] <dark_aqua>Compatible with PlaceholderAPI"
    - "[MESSAGE] <green>Name: <yellow>%player_name%"
    - "[MESSAGE] <green>Prefix: <yellow>%vault_prefix%"
    - "[MESSAGE] <r>"
  three:
    - "[MESSAGE] <r>"
    - "<green>This is a announcer"
    - "<hover:show_text:'<aqua>Show minimessage page'><red>Compatible with hover text</hover>"
    - "<hover:show_text:'<aqua>Click here'><click:suggest_command:/say Hello><red>Compatible with click actions</click></hover>"
    - "[MESSAGE] <r>"