name: MiniAnnouncer
version: '${project.version}'
main: me.jonakls.miniannouncer.MiniAnnouncer
api-version: 1.17
authors: [ Jonakls ]
description: Simple plugin for automatic announcers
website: https://github.com/Jonakls
loadbefore:
  - PlaceholderAPI
depend:
  - PlaceholderAPI
commands:
  fenixannouncer:
    description: General command of plugin
    aliases:
      - announcer
      - ma
      - minia