name: MiniAnnouncer
version: @version@
main: me.jonakls.miniannouncer.MiniAnnouncer
api-version: 1.17
authors: [ Jonakls ]
description: Simple plugin for automatic announcers
website: https://github.com/Jonakls

softdepend:
  - PlaceholderAPI
commands:
  miniannouncer:
    description: General command of plugin
    aliases:
      - ma
      - minia
      - announcer
