name: FenixAnnouncer
version: '${project.version}'
main: me.jonakls.fenixannouncer.FenixAnnouncer
api-version: 1.17
authors: [ Jonakls ]
description: Simple plugin for announcer
website: https://github.com/Jonakls
loadbefore:
  - PlaceholderAPI
depend:
  - PlaceholderAPI
commands:
  fenixannouncer:
    description: General command of plugin
    aliases:
      - announcer
      - fa