name: FenixAnnouncer
version: '${project.version}'
main: me.gardendev.fenixannouncer.FenixAnnouncer
api-version: 1.17
authors: [ Jonakls ]
description: Simple plugin for announcer
website: https://github.com/Jonakls
commands:
  fenixannouncer:
    description: General command of plugin
    aliases:
      - announcer
      - fa